### PR TITLE
Added Animation to home page Content

### PR DESCRIPTION
**Pull request by vrutansh**
only for the h1's

### CODE REVIEW

**Comment by royalsanga24** [comment]
https://github.com/agnasmedia/Agnas-Media/assets/59764276/a4ad7102-5682-49df-a411-3e53378f6300

Animation is working fine but the design is messed up.

**Comment by vrutansh** [comment]
Fixing it..

**Comment by royalsanga24** [comment]
@vrutansh Also, it would be better if the animation is a bit longer. It would be more noticeable then.

**Comment by vrutansh** [comment]
Already did in the second commit "improved animation".

**Pull request closed without merging**
