### PR TITLE
Newtest 

### PR DESCRIPTION
**Pull request by vrutansh**
Added Font file,

### CODE REVIEW

**Comment by royalsanga24** [comment]
@vrutansh  This PR has some issues:
1) Pull from latest main in a new local feature branch
2) The spacing, margins and positioning needs to be fixed
Screenshot 2024-05-15 at 11 08 43 AM
3) The spacing, margins and positioning needs to be fixed
Screenshot 2024-05-15 at 11 09 07 AM
4) The spacing, margins and positioning needs to be fixed
Screenshot 2024-05-15 at 11 09 18 AM

**Comment by vrutansh** [comment]
Screenshot (268)
Screenshot (267)
Screenshot (266)
Screenshot (265)
Screenshot (264)
Screenshot (263)
Screenshot (261)
Screenshot (227)
Screenshot (227)

IT IS Already WORKING PERFECTLY FINE IN ALL SCREENS.

**Comment by royalsanga24** [comment]
@vrutansh  I'll check for home page and awards. But like I mentioned, on footer, 'be advance' is not symmetric on your screens as well.

**Comment by royalsanga24** [comment]
@vrutansh I fixed your commit. You had given unncessary margins. Kindly test once before pushing.

**Comment by royalsanga24** [comment]
@vrutansh I checked your awards section. It is good for screens if the width <= 1920. If the width goes over that, it breaks. Like in my case (screenshot attached above).

**Pull request closed without merging**
